### ISSUE TITLE
unsatisfiable FBbt classes in Ubergraph build

### ISSUE THREAD

**Issue by balhoff** [FlyBase/drosophila-anatomy-developmental-ontology#1530] opened 2022-10-12 16:15 UTC
I'm looking into various incoherencies when merging OBO ontologies, as part of the [Ubergraph](https://github.com/INCATools/ubergraph) build. Here is one unsatisfiable class:

## [adult fruitless pIP10 (male) neuron](http://purl.obolibrary.org/obo/FBbt_00110854) EquivalentTo [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [adult fruitless pIP10 (male) neuron](http://purl.obolibrary.org/obo/FBbt_00110854) SubClassOf [has synaptic IO in region](http://purl.obolibrary.org/obo/RO_0013001) some [adult periesophageal neuropils](http://purl.obolibrary.org/obo/FBbt_00045047)
    - [adult periesophageal neuropils](http://purl.obolibrary.org/obo/FBbt_00045047) SubClassOf [synaptic neuropil block](http://purl.obolibrary.org/obo/FBbt_00041000)
      - [synaptic neuropil block](http://purl.obolibrary.org/obo/FBbt_00041000) EquivalentTo [insect synaptic neuropil block](http://purl.obolibrary.org/obo/UBERON_6041000) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [Drosophila melanogaster](http://purl.obolibrary.org/obo/NCBITaxon_7227))
        - [insect synaptic neuropil block](http://purl.obolibrary.org/obo/UBERON_6041000) SubClassOf [anatomical group](http://purl.obolibrary.org/obo/UBERON_0000480)
          - [anatomical group](http://purl.obolibrary.org/obo/UBERON_0000480) SubClassOf [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061)
        - [synaptic neuropil block](http://purl.obolibrary.org/obo/FBbt_00041000) SubClassOf [anatomical group](http://purl.obolibrary.org/obo/FBbt_00007276)
  - [anatomical structure](http://purl.obolibrary.org/obo/FBbt_00007001) DisjointWith [anatomical group](http://purl.obolibrary.org/obo/FBbt_00007276)
  - [anatomical structure](http://purl.obolibrary.org/obo/FBbt_00007001) EquivalentTo [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [Drosophila melanogaster](http://purl.obolibrary.org/obo/NCBITaxon_7227))

The problem here is that in Uberon, 'anatomical group' is a subclass of 'anatomical structure', but in FBbt these are disjoint. Some FBbt terms are mapped under 'anatomical group', and then the Uberon structure makes them also 'anatomical structure'.

Does FBbt want to align further with Uberon? For Ubergraph we could either not load the mappings, or go back to filtering out disjointness (not preferred).

**Comment by balhoff** [comment] 2022-10-12 16:16
There are 834 unsatisfiable FBbt classes in the Ubergraph build. I haven't checked whether they are all a result of this same issue.

**Comment by gouttegd** [comment] 2022-10-12 21:35
In the particular example shown, I think the problem is more that UBERON’s `insect synaptic neuropil block` is a subclass of `anatomical group`.

That’s one of the UBERON:6xxxxxx series of terms, so it was probably made that way in an attempt to mimic the FBbt hierarchy (where `synaptic neuropil block` is a subclass of FBbt’s `anatomical group`), but it’s actually wrong because FBbt’s `anatomical group` is _not_ the same thing as UBERON’s `anatomical group` – it is closer to UBERON’s `disconnected anatomical group`, to which it is actually mapped.

So in UBERON, `insect synaptic neuropil block` should be a subclass of `disconnect anatomical group` instead. That would make it _not_ an `anatomical structure`, and so would leave it unaffected by FBbt’s disjointness axiom between `anatomical structure` and `anatomical group`.

**Comment by gouttegd** [comment] 2022-10-12 21:38
(I wonder how many of the 834 unsats are ultimately caused by those UBERON:6xxxxxx terms – I suspect quite a few. Oh well, we needed to review those terms anyway…)

**Comment by Clare72** [comment] 2022-10-13 08:45
I think we should also rename "anatomical group" in FBbt to "disconnected anatomical group" to prevent further confusion.

**Comment by gouttegd** [comment] 2022-10-21 20:26
So here’s what I think is the complete list of root causes for the incompatibilities between FBbt and Uberon.

Most, if not all, of them should actually be fixed on the Uberon side, because it seems to me that FBbt is doing the “right thing” in all those instances (though I’ll admit I may obviously have a pro-FBbt bias).

I’ll create tickets in Uberon for those issues.


# Disjointness between “connected” and “disconnected” entities

In FBbt, many classes are subclasses of either `anatomical structure` (FBbt:00007001) or `disconnected anatomical group` (FBbt:00007276). The main difference between the two classes is that an anatomical structure is made of parts that are all _connected_, whereas a disconnected anatomical group, as the name implies, is made of parts that “are not all continuous with each other”.

We have a disjointness axiom between the two classes, so that nothing can be simultaneously made of parts that are all connected and made of parts that are not all connected.

Uberon has a similar `anatomical structure` (UBERON:0000061) (for things made of connected parts) and a `disconnected anatomical group` (UBERON:0034923) (for things made of not-all-connected parts). It also has a `anatomical group` (UBERON:0000480), which is a subclass of `anatomical structure` (and therefore is a group made of all-connected parts).

However, Uberon does not enforce a strict separation between connected and not-connected anatomical entities (no disjointness axioms), and as a result this distinction is violated in several instances.


## `non-connected functional system` (UBERON:0015203)

In Uberon, `non-connected functional system` is a `anatomical system` (UBERON:0000467), which itself is a `anatomical structure`. Since an anatomical structure is defined (both in Uberon and FBbt) as something whose all parts are _connected_, this classification is obviously wrong: a “non-connected functional system” cannot, by definition, be an anatomical structure.

In FBbt, `non-connected functional system` (FBbt:00007278) is a `disconnected anatomical group`, so there’s no problem. The problem arises when we map the FBbt term to the Uberon term, because in the merged ontology (or in Ubergraph) the FBbt term is now both a (connected) anatomical structure and a disconnected anatomical group, something our disjointess axiom does not allow (and rightly so).

Solutions: Either temporarily fix the problem on FBbt side by removing the mapping between FBbt’s `non-connected functional system` and Uberon’s `non-connected functional system`, or (better) re-classify Uberon’s `non-connected functional system` as a `disconnected anatomical group`.


## `insect non-connected developing system` (UBERON:6040003)

Similar to the previous one. In Uberon, `insect non-connected developing system` is a `anatomical group` (UBERON:0000480), which is a `anatomical structure`, so again something whose all parts are _connected_, which is incorrect.

Same solutions: either unmap FBbt’s `non-connected developing system` (FBbt:00040003) and Uberon’s `insect non-connected developing system`, or (better) re-classify the Uberon term as a `disconnected anatomical group` instead of a (connected) `anatomical group`.

(As an aside, I’d question the usefulness of Uberon’s `anatomical group`.)


## `insect synaptic neuropil block` (UBERON:6041000)

In Uberon, this is a (connected) `anatomical group`. In FBbt, `synaptic neuropil group` (FBbt:00041000) is a `disconnected anatomical group`. Based on the definition (“a closely associated group of synaptic neuropil domains”, which doesn’t seem to imply those domains are _connected_), I think FBbt’s classification is correct.

Same solutions: either unmap the two terms, or (better) re-classify the Uberon term under `disconnected anatomical group` to match what is done in FBbt.


## `insect synaptic neuropil` (UBERON:6040005)

In Uberon, this is a (connected) `anatomical group`. In FBbt, `synaptic neuropil` (FBbt:00040005) is a `material anatomical entity` (FBbt:00007016), which states nothing about the “connectedness” of the entity, contrary to the Uberon term.

Solutions:
- Review FBbt’s `synaptic neuropil` classification to see if we can make it into a connected structure. Given that we currently have both connected and not-connected subclasses, I think it is likely, however, that our classification as an anatomical entity is correct.
- Unmap FBbt’s `synaptic neuropil` and Uberon’s `insect synaptic neuropil` (which would probably mean that the Uberon term can be obsoleted).
- Re-classify the Uberon term as a `material anatomical entity` (UBERON:0000465), to match FBbt’s classification.


## `sensory system` (UBERON:0001032)

In Uberon, this is a `anatomical system`, so a (connected) `anatomical structure`. In FBbt, the equivalent term (FBbt:00007692) is a `non-connected functional system` (FBbt:00007278), which is a `disconnected anatomical group`.

I again believe FBbt’s classification makes more sense. It can be argued that all the sensory organs distributed through the body are ultimately all connected by axons, but with that logic then almost everything in the body is connected… I think it is more sensible to consider the sensory system as a set of _disconnected_ sensory organs.

Solutions: either unmap the two terms, or review either FBbt’s classification (make the FBbt term a `organ system`) or Uberon’s classification (make the Uberon term a `non-connected functional system`, after having re-classified `non-connected functional system` as a `disconnected anatomical group` as discussed above) – the latter has my preference.


## `endocrine system` (UBERON:0000949)

This is exactly the same situation as for `sensory system`.


## `anatomical cluster` (UBERON:0000477)

In Uberon, this is classified as an `anatomical entity` (UBERON:0001062), which makes no statement about the “connectedness” of the cluster, but defined as an “anatomical group that has its parts adjacents to one another”.

In FBbt, `anatomical cluster` (FBbt:00007227) is classified as a `disconnected anatomical group` and defined as an “anatomical group whose component anatomical structures lie in close proximity to each other”. So, FBbt’s classification matches the definition.

I think “adjacents” in the Uberon definition can be understood as equivalent to FBbt’s “in close proximity to one another”, so the mapping between the two terms is, I believe, correct. But in that case, the Uberon term can (should) be re-classified as a `disconnected anatomical group`.


# Disjointness between “made of cells” and “made of cell parts”

FBbt has a `multi-cell-component structure` (FBbt:00007060), a `anatomical structure` made of “multiple cell components but which is not iself a cell and does not have (complete) cells as parts”. It is disjoint with `multicellular structure` (FBbt:00007013), so that nothing can be simultaneously made of “parts of cells” and made of cells.

Likewise, Uberon has a `multi cell part structure` (UBERON:0005162) and a `multicellular anatomical structure` (UBERON:0010000), but does not enforce the distinction between the two. In addition, `multi cell part structure` is classified as a `anatomical cluster`, which contradicts its definition as a “structure”.

Either unmap FBbt’s `multi-cell-component structure` and Uberon’s `multi cell part structure`, or re-classify the Uberon term as a `anatomical structure`, as it should be.


## `primary nerve cord` (UBERON:0005053)

In Uberon, this is defined as a “cluster of neurons”, but classified as a `central nervous system cell part cluster` (UBERON:0011215), which is a `multi cell part structure`. This is clearly wrong: if it’s a “cluster of neurons”, then it is made of neurons, so made of cells, and therefore cannot be a `multi cell part structure` which is defined as not having complete cells as its parts.

Since FBbt’s `ventral nerve cord` (FBbt:00005097) is mapped to Uberon’s `ventral nerve cord` (UBERON:0000934) which is a subclass of `primary nerve cord`, this bogus classification makes a whole bunch of FBbt terms related to the VNC unsatisfiable.


# Disjointness between “organ system” and “organ system subdivision”

FBbt has a disjointnesss axiom between `organ system` (FBbt:00004856) and `organ system subdivision` (FBbt:00007330).

In Uberon, the equivalent of FBbt’s `organ system` is `anatomical system` (UBERON:00000467), and the equivalent of `organ system subdivision` is a term with the same label (UBERON:0011216). Both are `anatomical structure`s.


## `muscle system` (FBbt:00005069)

In FBbt, this terms refers to all the muscles of the body and is classified as an `organ system`. It is mapped to Uberon’s `musculature of body` (UBERON:0000383), which is also defined as referring to all the muscles of the body (and has “muscle system” as a synonym). The Uberon term is however classified as a `organ system subdivision`, because it is considered to be the subdivision of `musculoskeletal system` (UBERON:00002204) (which is divided into `musculature of body` – or “muscle system” – and `skeletal system`).

I am not sure what is best here. Neither the FBbt classification nor the Uberon classification seem obviously wrong, but they are clearly incompatible.

It is unclear, however, whether Uberon’s `musculature of body` really refers (or should refer) to _all_ the muscles or only the _somatic_ (“skeletal”) muscles. It seems wrong to me to include visceral muscles in the “musculoskeletal system”.

Until this is sorted on Uberon side, the best for now, I believe, is to unmap FBbt’s `muscle system` and Uberon’s `musculature of body`.


# Other problems

## `imaginal disc` (UBERON:0000939)

In Uberon, this is classifed as a `epithelial sac` (UBERON:0007499), which is ultimately a `epithelium` (UBERON:0000483). This is flatly wrong as an imaginal disc is more than a single epithelium.

In FBbt, we classify `imaginal disc` (FBbt:00001761) as a `multi-tissue structure` (00007010) to reflect the fact that it is made of more than an epithelium. The columnar epithelium that makes up most of the disc is called the `disc epithelium proper` (FBbt:00007029).

Solution: the Uberon term should be re-classified as `multi-tissue structure` (UBERON:0000481).


## `neuronal glomerulus` (UBERON:0001047)

In Uberon, this is classified as a `neuropil` (UBERON:0002606).

In FBbt, `glomerulus` (FBbt:00005386) is classified as a `synaptic neuropil subdomain` (FBbt:00040006).

Not sure which classification is more correct, if any. Suggestion is to unmap the terms for now.


## `head capsule` (UBERON:0003153)

In Uberon, this is classified as a `anatomical cluster`, which seems completely wrong. The term is also of dubious usefulness. Suggestion is to unmap it from FBbt’s `head capsule` (FBbt:00004482) and to obsolete it in Uberon.

**Comment by gouttegd** [comment] 2022-12-05 18:11
Following the merge of PR obophenotype/uberon#2695 in Uberon, I now get zero unsats when trying to merge Uberon, CL, and FBbt, so the Ubergraph build should be fixed as well.

**Comment by gouttegd** [comment] 2022-12-23 13:17
Closing here; feel free to re-open if you keep detecting unsats in Ubergraph.

**Closed by gouttegd** 2022-12-23 13:17 UTC
