### ISSUE TITLE
ppk-expressing mechanosensory neurons in the female reproductive tract

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#1676] opened 2023-09-14 20:15 UTC
I'm at a loss as to what these ought be called. The description suggests they're not multidendritic neurons (as most ppk-expressing neurons are). They're described in three papers: PMID: 19249273, PMID: 19249272, and PMID: 25373900. Scer\GAL4[ppk.PG] is a marker. From expression curation of that driver:

'Scer\GAL4[ppk.PG] drives expression in the adult peripheral neurons, including 2 neurons on each lateral oviduct and 15 neurons on each side of the uterus, organised in 3 clusters.' (PMID: 19249273)

'In the reproductive tract it (Scer\GAL4[ppk.PG]) isexpressed in 2-3 fruitless expressing neurons on either side of the uterus as well as a small number of neurons surrounding the oviduct. The reproductive tract neurons project fine processes between the muscle and epithelial layers that enter and arborize within the lumen of the uterus while other processes bifurcate close to the soma and innervate the lower regions of the common oviduct, both these aborizations run along the inner surface of the epithelial cell layer. Infrequently, expression is also seen in 1-2 neurons near the base of the antennal nerve and the the lateral horn. Afferents from all of the above neurons contribute to the abdominal nerve trunk, most terminating in the thoracico-abdominal ganglion but some extend further in an anterior direction, and a pair of bilateral fibers emerge from the network in the abdominal ganglion, traverse the entire length of the ventral side of the nerve cord, extend through the cervical connective before terminating in the posterior region of the adult gnathal ganglion. (PMID: 19249272)

**Comment by Clare72** [comment] 2023-09-15 14:19
The neurons described in Yang et al. (2009) (PMID:19249273; FBrf0207501) and Hasemeyer et al. (2009) (PMID:19249272; FBrf0207523) are the sex peptide sensory neurons (FBbt:00111303 + subclasses) - I think 15 neurons is a mistake in the expression curation, perhaps because authors use n=15 samples?

The fru-negative neurons described by Gou et al. (2014) are FBbt:00049944, currently 'adult oviduct mechanosensory neuron', but Damien has broadened this to 'adult female reproductive tract mechanosensory neuron' (change will be in next FBbt release).

All these neurons fall under FBbt:00049943 'sensory neuron of female reproductive system'

**Comment by SianGramates** [comment] 2023-09-15 20:49
Aha! I was struggling to find a term mapping onto what seemed to be described in the newest paper of the three I listed. I'll revisit the '15 neurons' curation and correct it if it's indeed misleading (backstory is that I'm plowing through binary drivers with no expression attached, and have hit the lexA version of the ppk construct).

I'll close this ticket.

**Closed** 2023-09-15 20:50 UTC
