### ISSUE TITLE
subdivision of abdominal lateral multidendritic neuron ldaA 

### ISSUE THREAD

**Issue by SianGramates** [FlyBase/drosophila-anatomy-developmental-ontology#107] opened 2017-06-23 15:55 UTC
FBrf0209127 identifies a second abdominal lateral multidendritic neuron ldaA  FBbt:00002434) in adults.
Authors state: On the basis of the neuronal cell-surface staining, we found five da neurons in each of the abdominal hemisegments A3 and A4 (Figure ​(Figure3D;3D; the number of hemisegments examined was ten for each of A3 and A4). Our cell-marking experiment, which is described in Figure ​Figure4,4, clarified the origin of each neuron; aligned in the dorsal-to-ventral orientation were ddaD (larval class I), ddaC (larval class IV), ddaE (larval class I), ldaA (larval class II), and v'ada (larval class IV). Labeling neuronal nuclei, however, led us to notice that ldaA was associated with another neuron, ldaA-like (Figure ​(Figure3D;3D; see also Figure 5G-M; explained in Figure 6A-D).

and 

Because labeling of neuronal nuclei showed a pair of neurons to be tightly associated in the vicinity of the spiracle (Figure 5G-M), we speculate that larval ldaA became one of the two neurons in the adult and that the other adult neuron (ldaA-like) was derived from a cell that had not been identified as any of the larval da neurons. We attempted to label a pair of ldaA and ldaA-like in different colors by using the flipout-induced GFP expression in otherwise CD2-expressing neurons in the adult (Figure 6A-D). This labeling method showed that the cell bodies of these two neurons were attached to each other and that their dendritic arbors were substantially overlapped, as we had expected (number of pairs labeled = 3).

They refer to the newly identified neuron as "ldaA-like", so if this ticket is accepted, I'd think the term would be "abdominal lateral multidendritic neuron ldaA-like"

**Comment by Clare72** [comment] 2019-05-30 07:37
Seems to be a duplicate of issue #15 (same FBrf)

**Closed** 2019-09-03 07:38 UTC
Labels: new term request
